---
- name: Increase check_local_procs threshold
  lineinfile:
    state: present
    path: "{{ nagios_object_dir }}/localhost.cfg"
    regexp: 'check_local_procs'
    line: "        check_command                   check_local_procs!2500!4000!RSZDT"
    owner: "{{ nagios_user }}"
    group: "{{ nagios_user }}"
    mode: 0640

- name: Increase check_local_procs threshold
  lineinfile:
    state: present
    path: "{{ nagios_object_dir }}/localhost.cfg"
    regexp: 'check_local_load'
    line: "        check_command                   check_local_load!15.0,14.0,13.0!20.0,16.0,14.0"
    owner: "{{ nagios_user }}"
    group: "{{ nagios_user }}"
    mode: 0640

- name: Increase report_max_objects
  lineinfile:
    state: present
    path: /usr/share/thruk/lib/Thruk/Config.pm
    regexp: 'report_max_objects'
    line: "        'report_max_objects'                => 5000,"
    owner: root
    group: root
    mode: 0644
